name: 🚀 Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        name: 🐳 Build
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        runs-on: ubuntu-latest
        # only build/deploy main branch on pushes
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ secrets.GH_TOKEN }}

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v2

            - name: Setup gcloud
              uses: google-github-actions/setup-gcloud@master
              with:
                  service_account_key: ${{ secrets.GCP_CREDENTIALS }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  export_default_credentials: true

            - name: Configure docker for GCP
              run: gcloud auth configure-docker

            - name: 🐳 Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            # Setup cache
            - name: ⚡️ Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-
            - name: 🐳 Docker build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_ID }}:${{ github.sha }}
                  build-args: |
                      COMMIT_SHA=${{ github.sha }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

            # This ugly bit is necessary if you don't want your cache to grow forever
            # till it hits GitHub's limit of 5GB.
            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        needs: [build]
        # only build/deploy main branch on pushes
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v2

            - name: Deploy to Cloud Run
              uses: google-github-actions/deploy-cloudrun@main
              with:
                  service: ${{ secrets.GCP_SERVICE_ID }}
                  image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_ID }}:${{ github.sha }}
                  credentials: ${{ secrets.GCP_CREDENTIALS }}
                  region: ${{ secrets.GCP_REGION }}